### ISSUE TITLE
Breadcrumbs should respect the `isSelectable` setting for items

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-breadcrumbs#10]
Items passed into px-breadcrumbs can have the following key/value

```
{
"id": "item1",
"label": "Item 1",
"isSelectable" : false
...
}
```

If `isSelectable` is false, and the item is tapped in the breadcrumbs UI (either as a top-level item or as an item in a dropdown) the item should not be selected. The context browser and tree already support this. It looks like it may be a bit more complex because breadcrumbs was implemented differently.

**Comment by davidrleonard** [comment]
See: 

* Commit where this was implemented in px-app-asset-graph: https://github.com/PredixDev/px-app-helpers/commit/20eee26c6bd9236074a36bfb30c4e1611bb38cfb
* Commit where this was implemented in px-context-browser: https://github.com/PredixDev/px-context-browser/commit/83a7600e007e6e5784d44eb4c59e2aa3205549f2
* Example of how this works in context browser: https://github.com/PredixDev/px-context-browser/blob/16bea6afb9dfa4ff69c8cf0544b0df02afdeb781/examples/is-selectable.html#L25

**Comment by randyaskin** [comment]
Added in v1.1.2.
