### ISSUE TITLE
PxBreadcrumbs emitting PxAppNav data

### ISSUE THREAD

**Issue by colinjlacy** [PredixDev/px-breadcrumbs#20]
## Expected behavior and actual behavior:

When I'm working in an app that includes both the `px-app-nav` and the `px-breadcrumbs` components, sometimes when I click on a breadcrumb, the initial event data is fired, but it is subsequently overwritten by data from the `px-app-nav`, specifically the first item in the nav item list.  I'd expect that the breadcrumb would emit only breadcrumb data.  Note that this is not at all an issue when I remove the `px-app-nav` from the app.

## Steps to reproduce the problem:

1. open the demo app: https://dts-demo.run.aws-usw02-pr.ice.predix.io/
2. log in with GE SSO and select a genre
3. select a band (I recommend Nirvana, but whatever)
4. click on a previous breadcrumb item 
5. **you should be navigated back to that route as expected**
6. navigate back to the band you chose
7. click on a song in the band details listing
8. once you're at the *Song Listing* page, click on a breadcrumb
9. **you will not be navigated back, and console logs starting with `breadcrumb click event` will indicate the problem at hand.**

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

- Chrome 57.0.2987.133
- Angular 4.4.6
- px-app-nav 2.1.1
- px-breadcrumbs 1.0.9

**Comment by davidrleonard** [comment]
Polymer 1.x does re-use event names. Polymer 2.x does not. Looking for a workaround with @colinjlacy now.

**Comment by colinjlacy** [comment]
@davidrleonard found a solid workaround, and I'd imagine that when we upgrade the problem will go away.  Closing.
