### ISSUE TITLE
Need a unique event to notify me when a user clicks on an item

### ISSUE THREAD

**Issue by colinjlacy** [PredixDev/px-breadcrumbs#21]
## Expected behavior and actual behavior:

When I'm using this component, I have to pass in an array of items for the `selected-route` in order for the breadcrumbs to display as expected.  Similarly, I have to listen for emits of the `selected-changed` event to know when a user has interacted with the component, and to route them accordingly.  I'm currently seeing a `selected-changed` event being emitted for both cases - when the binding data indicating the `selected-route` changes, and when the user clicks on an item.  I would expect to see two different events - specifically one that is unique for user-based interaction, similar to what is done in the `px-app-nav` with the `px-app-nav-item-tapped` event.

**Comment by randyaskin** [comment]
![screen shot 2018-01-12 at 2 16 08 pm](https://user-images.githubusercontent.com/2130613/34897530-43dbc69a-f7a3-11e7-9b4d-6925527e1abc.png)

**Comment by colinjlacy** [comment]
damn

**Comment by randyaskin** [comment]
There's a bug in the Google analyzer that builds our API pages, but the description for that event should read: `This event is fired whenever a click occurs - from a top path item, or dropdown item - that changes the context. The new context is attached as 'item'`

**Comment by colinjlacy** [comment]
gotcha.  thank you sir!
