### ISSUE TITLE
'no-drop'  cursor is not getting displayed when breadcurmb is not clickable.

### ISSUE THREAD

**Issue by SamBert03** [PredixDev/px-breadcrumbs#23]
Hi,

We are using px-breadcrumbs and px-context browser for navigation. Normally for a non selectable breadcrumb, cursor is the red no-drop icon, But when we have many breadcrumbs, it Ellipses to accommodate in the screen. When it ellipses , breadcrumbs has the cursor of 'pointer' instead of 'no-drop'.

## Expected behavior and actual behavior:
When breadcrumb ellipses, it should still have red no-drop cursor.

## Steps to reproduce the problem:
Longer chain of breadcrumbs[or long name] which should go beyond the available screen size. And it should have disabled breadcurmb.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Browser: Chrome.
It is reproducible in Predix UI also for the breadcrumb sample.

## Screenshots (_optional, but very helpful_):
![px-breadcrum2](https://user-images.githubusercontent.com/36529459/36304084-6338bf32-1334-11e8-8126-61b2dc230514.png)
![px-breadcurm1](https://user-images.githubusercontent.com/36529459/36304090-68945608-1334-11e8-8f1a-bcc6218abf97.png)

**Comment by randyaskin** [comment]
Fixed in v1.1.6, thanks.
