### ISSUE TITLE
dropdown items all turn bold when one is selected.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-breadcrumbs#5]
## Expected behavior and actual behavior:

When selected, dropdown items shouldn’t all become bold, just the selected one.

## Environment:

Breadcrumbs: redesign branch
Browsers: All

## Screenshot:

![screen shot 2017-07-27 at 10 48 18 am](https://user-images.githubusercontent.com/10835611/28695943-2be9a840-72e7-11e7-952e-0ac06fa0fe8c.png)

**Comment by randyaskin** [comment]
Fixed in latest by exposing an additional style variable in px-dropdown.
