### ISSUE TITLE
Component fails in IE and Edge

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-breadcrumbs#9]
## Expected behavior and actual behavior:
Component should function in MS browsers, like it does in all the other grown up browsers.

## Steps to reproduce the problem:
Open the page in IE 11 or MS Edge:
https://www.predix-ui.com/#/elements/px-breadcrumbs
Component fails to load on the page.  Errors appear in the console.  
These may be errors running ES6 constructs such as "const".
Also showing errors in the console loading GEInspiraSans font in IE 11.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Windows 10.  Both IE 11 and Edge 25.

**Comment by davidrleonard** [comment]
See the related answer in https://github.com/PredixDev/px-context-browser/issues/81
